### ISSUE TITLE
Are you looking for sample code?

### ISSUE THREAD

**Issue by kr601394** [PacktPublishing/TypeScript-2x-By-Example#1]
You can download sample code in https://www.packtpub.com/support/code-downloads via searching book title.
The correct url is https://account.packtpub.com/getfile/9781787280038/code
(Maybe you need to login to the site)

Oh.. I found another url. https://github.com/sachinohri/TypeScriptTodo

**Comment by sonam-packt** [comment]
Thank you for suggesting.
